# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 00:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_interests', forum.models.ChoiceArrayField(base_field=models.CharField(choices=[('alzheimer', 'Alzheimer'), ('parkinson', 'Parkinson'), ('cancer', 'Cancer')], max_length=30), default=['parkinson'], size=None)),
                ('is_patient', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
